Lesson 5
Irina-pi/if-html pull request #6
Opened 2022-07-17 22:59 UTC by Irina-pi

2022-07-18 20:26 UTC, 5tronciy requested changes
Looks better than at last lesson.

2022-07-18 20:26 UTC, 5tronciy commented on styles/fonts.css
> +  src: local("Roboto Regular"), local("Roboto-Regular") url('./.../fonts/roboto-regular-cyrillic-ext.woff2') format('woff2');
Wrong path in url()

2022-07-18 20:26 UTC, 5tronciy commented on styles/styles.css
> +  max-width: 1440px;
Not sure, that you need this limit. It looks good without it on wide screens.

2022-07-18 20:26 UTC, 5tronciy commented on styles/styles.css
> +  max-width: 1440px;
The same as in the row 13

2022-07-18 20:26 UTC, 5tronciy commented on styles/styles.css
> +}
This line is thicker in design.

2022-07-19 11:36 UTC, Irina-pi commented on styles/styles.css
> +  max-width: 1440px;
Ok. Thank you!

2022-07-19 11:36 UTC, Irina-pi commented on styles/styles.css
> +  max-width: 1440px;
Ok.

2022-07-19 11:38 UTC, Irina-pi commented on styles/styles.css
> +}
Maked border 2px. now matches.

2022-07-19 11:58 UTC, Irina-pi commented on styles/styles.css
> +}
Ok. corrected on " url(./../fonts/roboto-regular-latin-ext.woff2) ". Anothe too.

2022-07-19 11:58 UTC, Irina-pi commented on styles/fonts.css
> +  src: local("Roboto Regular"), local("Roboto-Regular") url('./.../fonts/roboto-regular-cyrillic-ext.woff2') format('woff2');
Ok. corrected on " url(./../fonts/roboto-regular-latin-ext.woff2) ". Anothe too.

2022-08-12 15:16 UTC, merged